project:
  type: book
  output-dir: docs

book:
  title: "Bias & Objectivity in Law and Psychology"
  chapters:
    - index.qmd
    - e1.qmd

format:
  html:
    number-sections: true
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



